/*
 * generated by Xtext
 */
package org.xtext.rplsd.cvdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CvDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/rplsd/cvdsl/parser/antlr/internal/InternalCvDsl.tokens");
	}
}
