/*
 * generated by Xtext
 */
package org.xtext.rplsd.cvdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.rplsd.cvdsl.services.CvDslGrammarAccess;

public class CvDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CvDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.rplsd.cvdsl.parser.antlr.internal.InternalCvDslParser createParser(XtextTokenStream stream) {
		return new org.xtext.rplsd.cvdsl.parser.antlr.internal.InternalCvDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public CvDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CvDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
