/**
 * generated by Xtext
 */
package org.xtext.rplsd.cvdsl.validation;

import org.xtext.rplsd.cvdsl.validation.AbstractCvDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CvDslValidator extends AbstractCvDslValidator {
}
