/*
 * generated by Xtext
 */
package org.xtext.rplsd.cvdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.rplsd.cvdsl.ui.internal.CvDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CvDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CvDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CvDslActivator.getInstance().getInjector(CvDslActivator.ORG_XTEXT_RPLSD_CVDSL_CVDSL);
	}
	
}
