/*
 * generated by Xtext
 */
package org.xtext.rplsd.cvdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CvDslRuntimeModule extends org.xtext.rplsd.cvdsl.AbstractCvDslRuntimeModule {

}
