/*
 * generated by Xtext
 */
package org.xtext.rplsd.cvdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CvDslStandaloneSetup extends CvDslStandaloneSetupGenerated{

	public static void doSetup() {
		new CvDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

