/*
 * generated by Xtext
 */
package org.xtext.rplsd.cvdsl.ui.contentassist

import org.xtext.rplsd.cvdsl.ui.contentassist.AbstractCvDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class CvDslProposalProvider extends AbstractCvDslProposalProvider {
}
