/*
 * generated by Xtext
 */
package org.xtext.rplsd.cvdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CvDslUiModule extends org.xtext.rplsd.cvdsl.ui.AbstractCvDslUiModule {
	public CvDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
